"""
notebook_generator.py — Builds a complete executable Jupyter Notebook (.ipynb)
from the Paper2Code source files.

The generated notebook contains alternating Markdown and Code cells:
  Cell 1 (md)  : Title, paper citation, executive summary
  Cell 2 (md)  : Architecture table & hyperparameters
  Cell 3 (code): Dataset & DataLoader (contents of dataset.py)
  Cell 4 (code): Model architectures (contents of model.py)
  Cell 5 (code): Tensor verification sandbox (contents of verify_tensors.py)

Usage:
    from src.notebook_generator import build_notebook
    path = build_notebook(src_dir, out_path)
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path


# ── helpers ──────────────────────────────────────────────────────────────────

def _md_cell(source: str) -> dict:
    """Return a notebook markdown cell dict."""
    return {
        "cell_type": "markdown",
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "source": source,
    }


def _code_cell(source: str) -> dict:
    """Return a notebook code cell dict (no outputs yet)."""
    return {
        "cell_type": "code",
        "id": str(uuid.uuid4())[:8],
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


# ── public API ────────────────────────────────────────────────────────────────

def build_notebook(src_dir: Path, out_path: Path) -> Path:
    """
    Compile a valid .ipynb from the source files in src_dir and write it to
    out_path.  Returns out_path.

    Args:
        src_dir  : directory that contains model.py, dataset.py, verify_tensors.py
        out_path : destination file path (e.g. src/paper2code_pipeline.ipynb)
    """
    src_dir  = Path(src_dir)
    out_path = Path(out_path)

    model_src   = _read(src_dir / "model.py")
    dataset_src = _read(src_dir / "dataset.py")
    verify_src  = _read(src_dir / "verify_tensors.py")

    # ── Cell 1: title + citation ──────────────────────────────────────────────
    cell1 = _md_cell(
        "# Paper2Code — IBM Bob 2.0 Hackathon\n\n"
        "**Auto-generated executable notebook**\n\n"
        "---\n\n"
        "## Paper Citation\n\n"
        "> *A hyperspectral imaging framework integrating band selection and deep learning "
        "for beverage stain classification in forensic analysis*  \n"
        "> Scientific Reports (2026) **16**:22241  \n"
        "> DOI: 10.1038/s41598-026-22241-0\n\n"
        "---\n\n"
        "## Executive Summary\n\n"
        "This notebook was automatically generated by the **Paper2Code** pipeline after "
        "parsing the research paper PDF.  It contains:\n\n"
        "1. The complete **PyTorch dataset & DataLoader** boilerplate\n"
        "2. All four **neural-network architectures** described in the paper "
        "(MLP, 1D-CNN, LSTM, CNN-LSTM)\n"
        "3. An automated **tensor-shape verification sandbox** that confirms "
        "every model produces the expected `(N, 9)` output\n\n"
        "Run all cells top-to-bottom in **Google Colab** or **Jupyter Lab**."
    )

    # ── Cell 2: architecture table + hyperparameters ──────────────────────────
    cell2 = _md_cell(
        "## Extracted Architecture Metrics\n\n"
        "| Model | Layer Configuration | Input Shape | Output Shape | Params |\n"
        "|---|---|---|---|---|\n"
        "| **MLP** | Linear×4 + ReLU×3 + Dropout(0.3)×3 | `(N, 162)` | `(N, 9)` | ~248,841 |\n"
        "| **1D-CNN** | Conv1d×2 + MaxPool×2 + Linear×2 | `(N, 162)` | `(N, 9)` | ~681,609 |\n"
        "| **LSTM** | LSTM(1→128) + Dropout + Linear | `(N, 162)` | `(N, 9)` | ~68,233 |\n"
        "| **CNN-LSTM** | Conv1d + MaxPool + LSTM + Linear | `(N, 162)` | `(N, 9)` | ~34,121 |\n"
        "| **Dataset** | BeverageStainDataset (pixel-wise) | `(N, 162)` | label `()` | — |\n\n"
        "## Training Hyperparameters (Table 3)\n\n"
        "| Parameter | Value |\n"
        "|---|---|\n"
        "| Optimizer | Adam (lr=0.001, β₁=0.9, β₂=0.999) |\n"
        "| LR Scheduler | ReduceLROnPlateau (factor=0.5, patience=5) |\n"
        "| Dropout | 0.3 |\n"
        "| Batch size | 64 |\n"
        "| Max epochs | 100 |\n"
        "| Early stopping | patience=10 (monitor val_loss) |\n"
        "| Loss function | CrossEntropyLoss |\n"
        "| Input bands | 162 (ANOVA-selected from 204) |\n"
        "| Classes | 9 beverage stain types |\n"
    )

    # ── Cell 3: dataset + dataloader ─────────────────────────────────────────
    cell3 = _code_cell(
        "# ── Cell 3: Dataset & DataLoader ─────────────────────────────────────\n"
        "# Source: dataset.py  (auto-generated by Paper2Code)\n\n"
        + dataset_src
    )

    # ── Cell 4: model architectures ──────────────────────────────────────────
    cell4 = _code_cell(
        "# ── Cell 4: Model Architectures ──────────────────────────────────────\n"
        "# Source: model.py  (auto-generated by Paper2Code)\n\n"
        + model_src
    )

    # ── Cell 5: verification sandbox ─────────────────────────────────────────
    # Patch the relative import so it runs correctly inside the notebook
    verify_patched = verify_src.replace(
        "from src.model import",
        "from model import",
    ).replace(
        "from src.dataset import",
        "from dataset import",
    )
    cell5 = _code_cell(
        "# ── Cell 5: Tensor Verification Sandbox ──────────────────────────────\n"
        "# Source: verify_tensors.py  (auto-generated by Paper2Code)\n"
        "# Note: run this cell from the same directory as model.py & dataset.py\n\n"
        + verify_patched
    )

    # ── Assemble notebook ─────────────────────────────────────────────────────
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
        },
        "cells": [cell1, cell2, cell3, cell4, cell5],
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")
    return out_path
